#Alert
MessageSuccessAlert                     = "//span[@x-html='message.text']"
MessageErrorAlert                       = "//div[@ui-id='message-error']"
MessageSuccessAlert2                    = "//div[@ui-id='message-success']"
CloseMessageSuccessAlert2Button         = "//div[@ui-id='message-success']//button[@aria-label='Close message']"
RegisterAlertMessageFirtName            = "//ul[@id='accountcreate-1']"
RegisterAlerMessageWeakPassword         = "//li[normalize-space()='Please enter at least 8 characters.']"
RegisterAlertMessagePasswordNotMatch    = "//li[@data-msg-field='password_confirmation']"
RegisterAlerrMessageInvalidRegister     = "//span[@x-html='message.text']"
AlertProductNotFound                    = "//div[@class='message notice']"         
NavMenu2                                = "//nav[@aria-label='Main menu']//li[contains(@class,'group/parent')][2]"
NavMenu4                                = "//nav[@aria-label='Main menu']//li[contains(@class,'group/parent')][4]"
MessageInfoEmty                         = "//div[@class='message info empty']"
AlertMessage                            = "//li[@ha='req-error']"