#Alert
MessageErrorAlert                       = "//div[@ui-id='message-error']"
CloseMessageBtn                         = "//button[@aria-label='Close message']"
MessageSuccessAlert                    = "//div[@ui-id='message-success']"
CloseMessageSuccessAlertButton         = "//div[@ui-id='message-success']//button[@aria-label='Close message']"
RegisterAlertMessageFirtName            = "//ul[@id='accountcreate-1']"
RegisterAlerMessageWeakPassword         = "//li[normalize-space()='Please enter at least 8 characters.']"
RegisterAlertMessagePasswordNotMatch    = "//li[@data-msg-field='password_confirmation']"
RegisterAlerrMessageInvalidRegister     = "//span[@x-html='message.text']"
AlertProductNotFound                    = "//div[@class='message notice']"         
NavMenu2                                = "//nav[@aria-label='Main menu']//li[contains(@class,'group/parent')][2]"
NavMenu4                                = "//nav[@aria-label='Main menu']//li[contains(@class,'group/parent')][4]"
MessageInfoEmty                         = "//div[@class='message info empty']"
AlertMessage                            = "//li[@ha='req-error']"
AlertProductNotFound                    = "//div[@class='message notice']"       
HeaderShoppingCartButton                = "//button[@id='menu-cart-icon']"  
HeaderCompareButton                     = "//a[@id='compare-link']"

#Loader
LoadingPage                            = "//div[contains(@x-show, 'isLoading')]"
