ProductItemCard                     = "//main[@id='maincontent']//form[1]"
ProductsListViewIcon                = "//strong[@title='Grid']/preceding-sibling::button[@title='List']"
ProductListViewContainer            = "//div[contains(@class,'mode-list')]"
ProductsGridViewIcon                = "//strong[@title='List']/following-sibling::button[@title='Grid']"
ProductGridViewContainer            = "//div[contains(@class,'mode-grid')]"
ProductItemCardName                 = "//a[@class='product-item-link']"