LinkToRegister                      = "//a[@href='/customer/account/create']"
ButtonRegister                      = "//a[@id='customer.header.register.link']"
RegisterEmail                       = "//input[@id='email_address']"
RegisterFirstName                   = "//input[@id='firstname']"
RegisterLastName                    = "//input[@id='lastname']"
RegisterDateOfBirth                 = "//input[@id='dob']"
RegisterPassword                    = "//input[@id='password']"
RegisterPasswordConfirmation        = "//input[@id='password-confirmation']"
RegisterPhoneNumber                 = "//input[@id='telephone']"
CheckBoxIsWhatsapp                  = "//input[@id='isWhatsapp']"
SubmitRegisterButton                = "//button[@title='Create an Account']"
ButtonTodayDayOfBirth               = "//div[@class='p-1']//div[@x-text='date']"
RegisterSubscribeCheckbox           = "//input[@id='is_subscribed']"