ProductWishlist         = "//div[@class='products-grid wishlist']//div[contains(@class,'product-item-info')]"
BtnWishlist             = "//div[contains(@class,'add-to-wishlist')]//button[@id='add-to-wishlist']"
WishFieldComment        = "//li[@data-row='product-item']//textarea[contains(@class,'product-item-comment')]"
WishFieldQty            = "//div[@class='products-grid wishlist']//li[@data-row='product-item'][1]//div[contains(@class,'product-item-info')]//div[@class='box-tocart']//input"
BtnATCWishlist          = "//div[@class='products-grid wishlist']//li[@data-row='product-item'][1]//div[contains(@class,'product-item-info')]//div[contains(@class,'product-item-actions')]//button[@data-role='tocart']"
BtnUpdateWishlist       = "//div[contains(@class,'actions-toolbar ')]//button[contains(@class,'update')]"
BtnRemoveWishlist       = "//div[@class='products-grid wishlist']//li[@data-row='product-item'][1]//div[contains(@class,'product-item-info')]//div[contains(@class,'product-item-actions')]//a[@data-role='remove']"
ShareWishlistButton     = "//button[@name='save_and_share']"
TextAreaEmailWishlist   = "//textarea[@id='email_address']"
TextAreaMessageWishlist = "//textarea[@id='message']"
ShareToEmail            = "//button[@title='Share Wish List']"